config/routes.rb
Rails.application.routes.draw do


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: %i[index show edit update destroy] do
      collection do
        get 'active_users' => "users#active_users"
        get 'inactive_users' => "users#inactive_users"
      end
     patch '/admin/users/:id/change_status', to: 'admin/users#change_status', as: 'admin_user_change_status'
    end
    resources :trips, only: %i[index show destroy]
    get 'homes/top'
    get 'search' => "searches#search"
    get 'reports/per_country' => "reports#per_country"
    get 'reports/per_practice_language' => "reports#per_practice_language"
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about', as: 'about'
    # 地域の地図を表示するための処理をするルーティングを定義
    resources :regions, only: %i[show]
    # 地図用のルーティング追記
    resources :maps, only: %i[index] do
      member do
        get '/show' => "maps#show"
        get '/region' => "maps#region"
      end
    end
    # 検索のルーティング
    get 'search' => "searches#search"
    resources :chats, only: %i[show index create destroy]
    resources :trips do
      resource :favorite, only: %i[create destroy]
      resources :trip_comments, only: %i[create destroy]
    end
    resources :users, only: %i[edit show update index] do
      resource :relationships, only: %i[create destroy]
      get :follows, on: :member
      get :followers, on: :member
      collection do
        get "/my_page" => "users#my_page"
        patch 'withdraw'
        post "/guest_sign_in" => "users/sessions#guest_sign_in"
        get "/likes" => "users#likes"
      end
      member do
        get "/unsubscribe" => "users#unsubscribe"
        get 'post_index'
      end
    end
  end

  resources :countries, only: [] do
    get 'regions', on: :member
  end

  resources :notifications, only: [:update]

end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    @range = params[:range]
    @word = params[:word]
    @search = "partial_match"

    if @range == "User"
      @users = User.looks(@search, @word)
      @users_count = @users.count
    else
      @trips = Trip.looks(@search, @word)
      @trips_count = @trips.count
    end
  end

end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/search.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container my-5">
  <% if @range == "Trip" %>
    <div>
      <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word, placeholder: 'フリーワード' %>
        <%= f.submit "検索", class: "btn-sm btn-primary" %>
        <%= f.hidden_field :range, value: 'Trip' %>
      <% end %>
    </div>
  <% elsif @range == "User" %>
    <div>
      <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word, placeholder: 'フリーワード' %>
        <%= f.submit "検索", class: "btn-sm btn-primary" %>
        <%= f.hidden_field :range, value: 'User' %>
      <% end %>
    </div>
  <% end %>


  <!--検索結果のタイトル-->
  <h2 class="my-4 text-center">検索結果</h2>

  <div class="col-4 mx-auto my-4 text-center">
    <% if @range == "User" %>
      "ユーザー検索"<br/>
    <% elsif @range == "Trip" %>
      "投稿記事を検索"<br/>
    <% end %>
    キーワード: <%= @word %><br>
    検索結果：<%= @range == "User" ? @users_count : @trips_count %>件
  </div>

  <div class="table-responsive">
    <table class="table table-hover">
      <!--検索対象モデルがUserの時-->
      <% if @range == "User" %>
        <thead class="table-info">
          <tr>
            <th class="text-center">プロフィール写真</th>
            <th class="text-center">ユーザー名</th>
            <th class="text-center">国</th>
            <th class="d-none d-md-table-cell text-center">地域</th> <!-- スマホでは非表示 -->
            <th class="d-none d-md-table-cell text-center">話したい話題</th> <!-- スマホでは非表示 -->
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td class="text-center align-middle">
                <%= link_to user_path(user.id) do %>
                  <%= image_tag user.get_profile_image, size: '50x50', class: 'rounded-circle img-fluid' %>
                <% end %>
              </td>
              <td class="align-middle text-center">
                <%= link_to admin_user_path(user.id) do %>
                  <%= user.family_name %> <%= user.first_name %>
                <% end %>
              </td>
              <td class="align-middle text-nowrap text-truncate text-center"><%= user.country.name %></td>
              <td class="d-none d-md-table-cell align-middle text-center"><%= user.region.name %></td>
              <td class="d-none d-md-table-cell align-middle text-center text-truncate" style="max-width: 150px;"><%= user.topic %></td>
            </tr>
          <% end %>
        </tbody>

      <!--検索対象が記事(trip)の時-->
      <% else %>
        <thead class="table-success">
          <tr>
            <th class="text-center">投稿ユーザー</th>
            <th class="text-center">投稿写真</th>
            <th class="text-center">タイトル</th>
            <th class="d-none d-md-table-cell text-center">住所</th> <!-- スマホでは非表示 -->
          </tr>
        </thead>
        <tbody>
          <% @trips.each do |trip| %>
            <tr>
              <td class="align-middle text-center">
                <%= link_to admin_user_path(trip.user) do %>
                  <%= image_tag trip.user.get_profile_image, size: '50x50', class: 'rounded-circle img-fluid' %>
                <% end %><br>
                <%= link_to admin_user_path(trip.user) do %>
                  <%= trip.user.family_name %><%= trip.user.first_name %>
                <% end %>
              </td>
              <td class="align-middle text-center">
                <%= link_to admin_trip_path(trip.id) do %>
                  <%= image_tag trip.get_trip_image, size: '80x80', class: 'img-fluid' %>
                <% end %>
              </td>
              <td class="text-nowrap text-truncate align-middle text-center">
                <%= link_to admin_trip_path(trip.id) do %>
                  <%= trip.title %>
                <% end %>
              </td>
              <td class="d-none d-md-table-cell align-middle text-center text-truncate" style="max-width: 150px;"><%= trip.address %></td> <!-- スマホでは非表示 -->
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </table>
  </div>
</div>