config/routes.rb
Rails.application.routes.draw do


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: %i[index show edit update destroy] do
      collection do
        get 'active_users' => "users#active_users"
        get 'inactive_users' => "users#inactive_users"
      end
     patch '/admin/users/:id/change_status', to: 'admin/users#change_status', as: 'admin_user_change_status'
    end
    resources :trips, only: %i[index show destroy]
    get 'homes/top'
    get 'search' => "searches#search"
    get 'reports/per_country' => "reports#per_country"
    get 'reports/per_practice_language' => "reports#per_practice_language"
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about', as: 'about'
    # 地域の地図を表示するための処理をするルーティングを定義
    resources :regions, only: %i[show]
    # 地図用のルーティング追記
    resources :maps, only: %i[index] do
      member do
        get '/show' => "maps#show"
        get '/region' => "maps#region"
      end
    end
    # 検索のルーティング
    get 'search' => "searches#search"
    resources :chats, only: %i[show index create destroy]
    resources :trips do
      resource :favorite, only: %i[create destroy]
      resources :trip_comments, only: %i[create destroy]
    end
    resources :users, only: %i[edit show update index] do
      resource :relationships, only: %i[create destroy]
      get :follows, on: :member
      get :followers, on: :member
      collection do
        get "/my_page" => "users#my_page"
        patch 'withdraw'
        post "/guest_sign_in" => "users/sessions#guest_sign_in"
        get "/likes" => "users#likes"
      end
      member do
        get "/unsubscribe" => "users#unsubscribe"
        get 'post_index'
      end
    end
  end

  resources :countries, only: [] do
    get 'regions', on: :member
  end

  resources :notifications, only: [:update]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :country
  belongs_to :region
  belongs_to :mother_language, class_name: "Language", foreign_key: "mother_language_id"
  belongs_to :practice_language, class_name: "Language", foreign_key: "practice_language_id"
  has_many :trips, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :trip_comments, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :chat_rooms, through: :user_rooms
  has_many :notifications, dependent: :destroy
  belongs_to :nationality_country, class_name: 'Country', foreign_key: 'nationality'
  has_many :visit_counts, dependent: :destroy

# ========================================================================================
  validates :first_name, presence: { message: '名前を入力してください' }, length: { maximum: 25 }
  validates :family_name, presence: { message: '姓を入力してください' }, length: { maximum: 25 }
  validates :introduction, presence: true, length: { in: 2..300 }
  validates :age, presence: true
  validates :topic, presence: true, length: { in: 2..100 }
# ========================================================================================

# ========================================================================================
  # プロフィール写真を扱う
  has_one_attached :profile_image
  # ユーザーのサブ写真を扱う
  has_many_attached :sub_images

  validates :profile_image, content_type: ['image/png', 'image/jpeg', 'image/jpg'], size: { less_than: 5.megabytes }
  validates :sub_images, content_type: ['image/png', 'image/jpeg', 'image/jpg'], size: { less_than: 5.megabytes }
  validate :validate_sub_images_count
# ========================================================================================


# ========================================================================================
  # フォローフォロワー機能
  # ============フォローする・している側からの視点===========================================
  # フォローする側の情報についての紐づけ
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # activeを通して、フォローされる人の情報を取得する⇒source:followerになる
  has_many :followings, through: :active_relationships, source: :followed

  # # =======================================================================================

  # # ==========フォロワー側の視点・フォローされる方=========================================
  # Railsの命名規則の観点から、followed→followers(単数形⇒複数形)として認識してくれる
  # フォローされる側の情報についての紐付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  # passiveを通して、フォローしてくるユーザー情報を取得⇒source: :followingになる
  has_many :followers, through: :passive_relationships, source: :following
  # ========================================================================================
# ========================================================================================

  # プロフィール写真を表示させるためのメソッドを定義する
  # Rails側で画像を読み込むように設定する
  # ==========================================================================================================
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
      profile_image
  end
  # ========================================================================================

# ========================================================================================
  # サブ写真を表示させるためのメソッドを定義する
  # Rails側で画像を読み込むように設定する
  def get_sub_images
    unless sub_images.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      sub_images.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
      sub_images
  end
# ========================================================================================

# ========================================================================================
  # 検索するためのメソッド 部分一致の検索のみに変更 退会済みユーザーは除外する
  def self.looks(search, word)
    @user = User.joins(:country).joins(:region).where.not(is_active: false).where.not(email: "guest@example.com").where("family_name LIKE ? OR first_name LIKE ? OR countries.name LIKE ? OR regions.name LIKE ?", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%").distinct
  end
# ========================================================================================

# ========================================================================================
  # フォローされているかどうかを確認するメソッド
  def followed_by?(user)
    # 今自分が(引数のユーザー)がフォローしようとしているユーザー(受け側)がフォローしているかどうかを判別する
    passive_relationships.find_by(following_id: user.id).present?
  end
# ========================================================================================

# ========================================================================================
  # ゲストログインのメソッド
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.family_name = "ゲストユーザー"
      user.first_name = 'ゲストユーザー'
      user.country_id = 1
      user.region_id = 1
      user.mother_language_id = 1
      user.practice_language_id = 2
      user.introduction = "ゲストユーザーです！"
      user.age = 50
      user.topic = "ゲストユーザーです！"
    end
  end
# ========================================================================================


  def validate_sub_images_count
    if sub_images.count > 6
      errors.add(:sub_images, 'は最大6枚までアップロードできます。')
    end
  end

  def full_name
    "#{family_name} #{first_name}"
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

# ユーザー一覧表示=============================================================================
  def index
    # 全ユーザー情報を取得して10人1ページで表示する(ゲストは除く)
    @users = user_all_remove_guest.order(id: :asc).page(params[:page]).per(10)
    # 全ユーザーの人数を数える
    @users_count = user_all_count
    #有効ユーザーの人数と割合
    active_users_count_ration
    # 退会済みのユーザーの人数と割合
    not_active_users_count_ration
    # ============================================================
    # 国別の利用者数を表示するための情報を取得メソッド6を使用 (ゲスト,退会ユーザー除いている)
    @user_counts_per_country = active_users_data.group(:country_id).count

    # グラフ用のデータを準備
    @chart_data = {
      labels: @user_counts_per_country.keys.map { |country_id| Country.find(country_id).name },
      data: @user_counts_per_country.values
    }

    # ============================================================
    # 学習中の言語別人数を表示するための情報を取得(ゲスト,退会ユーザー除いている)
    @user_practice_language = active_users_data.group(:practice_language_id).count
    # ============================================================
  end
# ===============================================================================================

# ユーザー詳細・編集(ステータス変更)・更新=============================================================================
  def show
    @user = User.find(params[:id])
    @trips = @user.trips
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員ステータスを変更しました"
      redirect_to admin_user_path(@user)
    else
      @user = User.find(params[:id])
      flash[:notice] = "失敗です"
      render :edit
    end
  end
# ===============================================================================================

  # ユーザーの物理削除
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "対象のユーザーを削除しました"
    redirect_to admin_users_path
  end

# 有効ユーザーの一覧表示=============================================================================
  def active_users
    # 全ユーザー情報を取得する
    @users = user_all_remove_guest
    # 全ユーザーの人数を数える
    @users_count = user_all_count

    # 有効ユーザーの情報を取得し10件ごとに表示する
    @active_users = active_users_data.all.order(id: :asc).page(params[:page]).per(10)
    #有効ユーザーの人数と割合
    active_users_count_ration
    # 退会済みのユーザーの人数と割合
    not_active_users_count_ration
  end
# ===============================================================================================

# 退会ユーザーの一覧表示=============================================================================
  def inactive_users
    # 全ユーザー情報を取得する
    @users = user_all_remove_guest
    # 全ユーザーの人数を数える
    @users_count = user_all_count
    #有効ユーザーの人数と割合
    active_users_count_ration

    # 退会済みユーザーを10件ごとに表示
    @not_actives = not_active_users_data.all.order(id: :asc).page(params[:page]).per(10)
    # 退会済みのユーザーの人数と割合
    not_active_users_count_ration
  end
# ===============================================================================================


  private

  def user_params
    params.require(:user).permit(:first_name, :family_name, :introduction, :topic, :profile_image, :practice_language_id, :is_active, sub_images: [])
  end

  # 全ユーザーを取得するメソッド(ゲストは除く)
  def user_all_remove_guest
    User.where.not(email: "guest@example.com").all
  end
  # 全ユーザーの人数を取得する
  def user_all_count
    user_all_remove_guest.count
  end

  # 有効ユーザーのデータを取得する
  def active_users_data
    User.where.not(is_active: false).where.not(email: "guest@example.com")
  end

  # 有効ユーザーの合計人数
  def active_users_count
    active_users_data.all.count
  end

  # 有効ユーザーの割合算出
  def active_user_ration
    @active_users_all * 100 / @users_count
  end

  #退会ユーザーのデータを取得する
  def not_active_users_data
    User.where(is_active: false).where.not(email: "guest@example.com")
  end

  # 退会ユーザーの合計人数
  def not_active_users_count
    User.where(is_active: false).all.count
  end

  # 退会済みユーザーの割合算出
  def not_active_user_ration
    @not_active_users * 100 / @users_count
  end

  #まとめたメソッド
  def active_users_count_ration
    # 有効ユーザーの合計人数
    @active_users_all = active_users_count
    # 有効ユーザーの割合算出
    @active_user_ration = active_user_ration
  end

  def not_active_users_count_ration
    # 退会済みのユーザーの合計人数
    @not_active_users =  not_active_users_count
    # 退会済みユーザーの割合算出
    @not_active_user_ration = not_active_user_ration
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_all_user_table.html.erb
<table class="w-100" style="border-top: 2px solid gray; border-bottom: 2px solid gray;">
  <thead>
    <tr>
      <th class="table-active" style="padding: 10px;">会員ID</th>
      <th class="table-active" style="padding: 10px;">プロフィール写真</th>
      <th class="table-active" style="padding: 10px;">氏名</th>
      <th class="table-active" style="padding: 10px;">メールアドレス</th>
      <th class="table-active" style="padding: 10px;">ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td style="padding: 10px;"><%= user.id %></td>
        <td style="padding: 10px;"><%= image_tag user.get_profile_image, size: '100x100', class: 'rounded-circle' %></td>
        <td style="padding: 10px;">
          <%= link_to admin_user_path(user) do %>
            <%= user.family_name %><%= user.first_name %>
          <% end %>
        </td>
        <td style="padding: 10px;"><%= user.email %></td>
        <td style="padding: 10px;">
          <% if user.is_active == true %>
            <p class="text-center" style="color:black; background-color:#CCFF99;"><strong>有効</strong></p>
          <% else %>
            <p class="text-center" style="color:black; background-color:#FFABCE;">退会済み</p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center mt-3" style="font-size: 1.5rem">
  <%= paginate users, class: 'pagination_admin' %>
</div>

app/views/admin/users/_users_index_table.html.erb
 <h3 class="text-center border-bottom pb-2 my-2">合計会員数</h3>
  <table class="table table-bordered text-center admin_user_table mb-3">
    <tr>
      <th class="head">項目</th>
      <th class="head">人数(人)</th>
      <th class="head">割合(%)</th>
    </tr>
    <tr>
      <th>会員人数</th>
      <td class="analyse_link">
        <%= link_to admin_users_path do %>
          <%= users_count %>
        <% end %>
      </td>
      <td>-</td>
    </tr>
    <tr>
      <th>有効</th>
      <td class="analyse_link active_users">
        <%= link_to active_users_admin_users_path do %>
          <%= active_users_all %>
        <% end %>
      </td>
      <td class="active_users"><%= active_user_ration %> %</td>
    </tr>
    <tr>
      <th>退会済み</th>
      <td class="analyse_link non_active_users">
        <%= link_to inactive_users_admin_users_path do %>
          <%= not_active_users %>
        <% end %>
      </td>
      <td class="non_active_users"><%= not_active_user_ration %> %</td>
    </tr>
  </table>

app/views/admin/users/active_users.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container-fluid my-3">
  <div class="row">
    <!-- 左側に配置するテーブル -->
    <div class="col-md-4">

      <!--会員数を表示する表を部分テンプレ化呼び出す-->
      <%= render 'users_index_table', users_count: @users_count, active_users_all: @active_users_all, active_user_ration: @active_user_ration, not_active_users: @not_active_users, not_active_user_ration: @not_active_user_ration %>
    </div>

    <!-- 真ん中と右側に配置するコンテンツ -->
    <div class="col-md-8">
      <div class="row">
        <!-- ページのタイトル -->
        <div class="col-12" style="display: flex; align-items: center; justify-content: space-between;">
          <span class="pr-3 pl-3" style="font-size: 1.3rem; background-color: #ECECEC; font-weight: bold;">有効ステータスの会員一覧</span>
        </div>

        <!-- 会員一覧の表示 -->
        <div class="col-12 mt-3">
          <table class="w-100" style="border-top: 2px solid gray; border-bottom: 2px solid gray;">
            <thead>
              <tr>
                <th class="table-active" style="padding: 10px;">会員ID</th>
                <th class="table-active" style="padding: 10px;">プロフィール写真</th>
                <th class="table-active" style="padding: 10px;">氏名</th>
                <th class="table-active" style="padding: 10px;">メールアドレス</th>
                <th class="table-active" style="padding: 10px;">ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @active_users.each do |user| %>
                <tr>
                  <td style="padding: 10px;"><%= user.id %></td>
                  <td style="padding: 10px;"><%= image_tag user.get_profile_image, size: '100x100', class: 'rounded-circle' %></td>
                  <td style="padding: 10px;">
                    <%= link_to admin_user_path(user) do %>
                      <%= user.family_name %><%= user.first_name %>
                    <% end %>
                  </td>
                  <td style="padding: 10px;"><%= user.email %></td>
                  <td style="padding: 10px;">
                    <% if user.is_active == true %>
                      <p class="text-center" style="color:black; background-color:#CCFF99;"><strong>有効</strong></p>
                    <% else %>
                      <p class="text-center" style="color:black; background-color:#FFABCE;">退会済み</p>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="d-flex justify-content-center mt-3" style="font-size: 1.5rem">
            <%= paginate @active_users %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container">
  <!-- フラッシュメッセージ -->
  <div class="w-50 mx-auto text-light text-center bg-danger mt-3">
    <%= flash[:notice] %>
  </div>

  <!-- タイトル -->
  <div class="row">
    <div class="col text-center my-3">
      <h1><%= @user.family_name %><%= @user.first_name %>さんのステータスを変更する</h1>
    </div>
  </div>

  <!-- 会員ステータス表示 -->
  <div class="row d-flex justify-content-center">
    <div class="col-12 col-md-6 mx-auto mt-2 border text-center">
      会員ステータス：
      <% if @user.is_active == true %>
        <p class="alert alert-success text-center"><strong>有効</strong></p>
      <% else %>
        <p class="alert alert-danger text-center">退会済み</p>
      <% end %>
    </div>
  </div>

  <!-- ステータス変更フォーム -->
  <div class="row d-flex justify-content-center my-4">
    <%= form_with model: @user, url: admin_user_path(@user), method: :patch, class: 'w-50' do |f| %>
      <div class="form-group">
        <label class="border-bottom">会員ステータス変更</label>
        <div class="form-check mb-3">
          <%= f.radio_button :is_active, true, class: 'form-check-input', style: 'width: 20px; height: 20px; cursor: pointer;' %>
          <%= f.label :is_active_true, "有効", class: 'form-check-label pl-3', style: 'cursor: pointer;' %>
        </div>
        <div class="form-check">
          <%= f.radio_button :is_active, false, class: 'form-check-input', style: 'width: 20px; height: 20px; cursor: pointer;' %>
          <%= f.label :is_active_false, "退会", class: 'form-check-label pl-3', style: 'cursor: pointer;' %>
        </div>
        <div class="text-center">
          <%= f.submit "変更内容を保存", class: 'btn btn-secondary mt-3', data: { confirm: "ステータスを変更してよろしいでしょうか？" }  %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-10 text-right my-4">
    <p>※抹消する場合にはこちら</p>
    <%= link_to "削除する", admin_user_path, method: :delete, class: 'btn btn-danger', data: { confirm: "本当に削除しますか？" } %>
  </div>

<!--以下がユーザー情報に関するコード-->
  <div class="row d-flex justify-content-center mb-4">
    <div class="col-lg-5 col-md-5 col-sm-12 justify-content-center text-center shadow border p-3" style="border-radius: 20px;">
     <h5 class="mb-3 border-bottom">プロフィール写真</h5>
     <%= image_tag @user.get_profile_image, size: '150x150', class: 'rounded-circle' %>
    </div>
    <div class="col-lg-5 col-md-5 col-sm-12 shadow border ml-3 p-3" style="border-radius: 20px;">
      <h5 class="mb-3 border-bottom text-center">基本情報</h5>
      <table>
        <tr>
          <th class="pr-3 pb-2">Name</th>
          <th class="pl-3 pb-2"><%= @user.family_name %>  <%= @user.first_name %></th>
        </tr>
        <tr>
          <th class="pr-3 pb-2">Country</th>
          <th class="pl-3 pb-2"><%= @user.country.name %></th>
        </tr>
        <tr>
          <th class="pr-3 pb-2">Location</th>
          <th class="pl-3 pb-2"><%= @user.region.name %></th>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/inactive_users.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container-fluid my-3">
  <div class="row">
    <!-- 左側に配置するテーブル -->
    <div class="col-md-4">

      <!--会員数を表示する表を部分テンプレ化呼び出す-->
      <%= render 'users_index_table', users_count: @users_count, active_users_all: @active_users_all, active_user_ration: @active_user_ration, not_active_users: @not_active_users, not_active_user_ration: @not_active_user_ration %>
    </div>

    <!-- 真ん中と右側に配置するコンテンツ -->
    <div class="col-md-8">
      <div class="row">
        <!-- ページのタイトル -->
        <div class="col-12" style="display: flex; align-items: center; justify-content: space-between;">
          <span class="pr-3 pl-3" style="font-size: 1.3rem; background-color: #ECECEC; font-weight: bold;">退会済みの会員一覧</span>
        </div>

        <!-- 会員一覧の表示 -->
        <div class="col-12 mt-3">
          <table class="w-100" style="border-top: 2px solid gray; border-bottom: 2px solid gray;">
            <thead>
              <tr>
                <th class="table-active" style="padding: 10px;">会員ID</th>
                <th class="table-active" style="padding: 10px;">プロフィール写真</th>
                <th class="table-active" style="padding: 10px;">氏名</th>
                <th class="table-active" style="padding: 10px;">メールアドレス</th>
                <th class="table-active" style="padding: 10px;">ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @not_actives.each do |user| %>
                <tr>
                  <td style="padding: 10px;"><%= user.id %></td>
                  <td style="padding: 10px;"><%= image_tag user.get_profile_image, size: '100x100', class: 'rounded-circle' %></td>
                  <td style="padding: 10px;">
                    <%= link_to admin_user_path(user) do %>
                      <%= user.family_name %><%= user.first_name %>
                    <% end %>
                  </td>
                  <td style="padding: 10px;"><%= user.email %></td>
                  <td style="padding: 10px;">
                    <% if user.is_active == true %>
                      <p class="text-center" style="color:black; background-color:#CCFF99;"><strong>有効</strong></p>
                    <% else %>
                      <p class="text-center" style="color:black; background-color:#FFABCE;">退会済み</p>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="d-flex justify-content-center mt-3" style="font-size: 1.5rem">
            <%= paginate @not_actives %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!--削除処理成功のメッセージ-->
  <% if flash[:notice].present? %>
    <%= content_tag :div, flash[:notice], class: "success_notice" %>
  <% end %>

<div class="container-fluid my-5">
  <div class="row">
    <!-- 左側に配置するテーブル -->
    <div class="col-md-4">
     <!--会員数を表示する表を部分テンプレ化呼び出す-->
     <%= render 'users_index_table', users_count: @users_count, active_users_all: @active_users_all, active_user_ration: @active_user_ration, not_active_users: @not_active_users, not_active_user_ration: @not_active_user_ration %>
      <!--国別のユーザー数を表示する-->
      <h3 class="text-center border-bottom pb-2 my-4">
        <%= link_to "国別の会員数情報を見る", admin_reports_per_country_path, class: 'btn btn-info mx-1 p-2 container-fluid', style: "font-size: 1.3rem", data: { turbolinks: false } %>
      </h3>
      <!--学習中の言語別ユーザー数を表示する-->
      <h3 class="text-center border-bottom pb-2 my-4">
        <%= link_to "学習中の言語別の会員数情報を見る", admin_reports_per_practice_language_path, class: 'btn btn-success mx-1 p-2 container-fluid', style: "font-size: 1.3rem", data: { turbolinks: false } %>
      </h3>
    </div>

    <!--ページ右側に配置する-->
    <div class="col-md-8">
      <div class="row">
        <!-- ページのタイトル -->
        <div class="col-12" style="display: flex; align-items: center; justify-content: space-between;">
          <span class="pr-3 pl-3" style="font-size: 1.5rem; background-color: #ECECEC; font-weight: bold;">会員一覧</span>
        </div>
        <!-- 会員一覧の表示 部分テンプレート -->
        <div class="col-12 mt-3">
          <%= render 'admin/users/all_user_table', users: @users %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<%= stylesheet_link_tag 'user_show', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

 <!--変更処理成功のメッセージ-->
<% if flash[:notice].present? %>
  <%= content_tag :div, flash[:notice], class: "success_notice" %>
<% end %>

<div class="container d-flex justify-content-center flex-column my-5">
  <div class="row">
    <div class="col text-center mt-2 mb-4">
  <h1 class="text-center"><strong><%= @user.first_name %>さんのユーザープロフィール</strong></h1>
    </div>
  </div>

  <!-- 会員ステータス表示 -->
  <div class="row d-flex justify-content-center mb-4">
    <div class="col-12 col-md-6 mx-auto mt-2 border text-center py-3">
      会員ステータス：
      <% if @user.is_active == true %>
        <p class="alert alert-success text-center"><strong>有効</strong></p>
      <% else %>
        <p class="alert alert-danger text-center">退会済み</p>
      <% end %>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col-12 text-right">
      <%= link_to "会員ステータスを変更する", edit_admin_user_path, class: 'btn btn-warning px-5 py-3' %>
    </div>
  </div>
  <!--ユーザー情報は部分テンプレート呼び出す-->
  <%= render 'layouts/user_show', user: @user, trips: @trips %>
</div>