config/routes.rb
Rails.application.routes.draw do


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: %i[index show edit update destroy] do
      collection do
        get 'active_users' => "users#active_users"
        get 'inactive_users' => "users#inactive_users"
      end
     patch '/admin/users/:id/change_status', to: 'admin/users#change_status', as: 'admin_user_change_status'
    end
    resources :trips, only: %i[index show destroy]
    get 'homes/top'
    get 'search' => "searches#search"
    get 'reports/per_country' => "reports#per_country"
    get 'reports/per_practice_language' => "reports#per_practice_language"
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about', as: 'about'
    # 地域の地図を表示するための処理をするルーティングを定義
    resources :regions, only: %i[show]
    # 地図用のルーティング追記
    resources :maps, only: %i[index] do
      member do
        get '/show' => "maps#show"
        get '/region' => "maps#region"
      end
    end
    # 検索のルーティング
    get 'search' => "searches#search"
    resources :chats, only: %i[show index create destroy]
    resources :trips do
      resource :favorite, only: %i[create destroy]
      resources :trip_comments, only: %i[create destroy]
    end
    resources :users, only: %i[edit show update index] do
      resource :relationships, only: %i[create destroy]
      get :follows, on: :member
      get :followers, on: :member
      collection do
        get "/my_page" => "users#my_page"
        patch 'withdraw'
        post "/guest_sign_in" => "users/sessions#guest_sign_in"
        get "/likes" => "users#likes"
      end
      member do
        get "/unsubscribe" => "users#unsubscribe"
        get 'post_index'
      end
    end
  end

  resources :countries, only: [] do
    get 'regions', on: :member
  end

  resources :notifications, only: [:update]

end

app/views/layouts/_back_btn.html.erb
<!--戻るボタン-->
<!-- 戻るボタン -->
<span class="ml-3 mt-5">
  <button class="btn btn-secondary py-2 px-3" style="font-size:1.3rem" onclick="reloadAndGoBack()">Back</button>
</span>

<script>
  function reloadAndGoBack() {
    // ページをリロードしてから履歴を戻る
    window.location.href = document.referrer; // リファラ（前のページのURL）にリロード付きで戻る
  }
</script>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件のエラー") %>により保存されませんでした</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="w-100">
  <div class="text-center text-light pt-5 pb-4">
    <h6>
      &copy; Copyright EDC Co.Ltd
    </h6>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--<= stylesheet_link_tag 'public_homes', media: 'all', 'data-turbolinks-track': 'reload' %>-->

<nav class="header navbar navbar-expand-lg navbar-dark d-flex justify-content-between">
  <!--左側のロゴ表示 条件分岐をしている-->
  <div>
    <% if admin_signed_in? %>
      <%= link_to admin_homes_top_path, class: 'navbar-brand text-light logo_font' do %>
        <h2 class="logo"><span class="local">Local</span>.<span class="friends">Friends</span></h2>
      <% end %>
    <% elsif user_signed_in? %>
      <%= link_to my_page_users_path, class: 'navbar-brand text-light logo_font' do %>
        <h2 class="logo"><span class="local">Local</span>.<span class="friends">Friends</span></h2>
      <% end %>
    <% else %>
      <%= link_to root_path, class: 'navbar-brand text-light logo_font' do %>
        <h2 class="logo"><span class="local">Local</span>.<span class="friends">Friends</span></h2>
      <% end %>
    <% end %>
  </div>

    <!--ボタンの長い記述→ハンバーガーメニューにできる魔法のコード！-->
    <button class="navbar-toggler" type="button"
      data-toggle="collapse"
      data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!--終了-->

  <div>
    <div class="navbar navbar-right navbar-expand-lg collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <!--管理者ログインした時のヘッダー-->
        <% if admin_signed_in? %>
          <%= link_to 'ユーザー一覧', admin_users_path, class: 'text-warning hover-effect mx-3 link-offset-2', style: 'font-size:1.3rem', data: { turbolinks: false } %>
          <%= link_to '投稿一覧', admin_trips_path, class: 'text-warning hover-effect mx-3 link-offset-2', style: 'font-size:1.3rem' %>
          <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, data: { confirm: "本当にログアウトしますか？" }, class: 'text-light hover-effect mx-3 link-offset-2', style: 'font-size:1.3rem' %>

        <!--ユーザー サインイン状態のヘッダーnav-->
        <% elsif user_signed_in? %>
          <li class="header-link">
            <%= link_to my_page_users_path, method: :GET, class: 'nav-link nav-btn active' do %>
            <i class="fa-solid fa-user"></i><span>マイページ</span>
            <% end %>
          </li>
          <li class="dropdown">
            <% if Notification.notification_except_chat(current_user).any? %>
              <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-solid fa-circle-exclamation"></i>通知
                <span class="badge badge-danger"><%= Notification.notification_except_chat(current_user).count %></span>
              </button>
            <% end %>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <% if Notification.notification_except_chat(current_user).any? %>
                <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                <% Notification.notification_except_chat(current_user).limit(5).order(created_at: :desc).each do |notification| %>
                  <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                <% end %>
              <% end %>
            </div>
          </li>
          <li>
            <%= link_to users_path, method: :GET, class: 'nav-link nav-btn active', data: { turbolinks: false } do %>
            <i class="fa-solid fa-people-carry-box"></i><span>コミュニティ</span><br/>
            <span>(ユーザーを探す)</span>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <!--chat相手一覧へのアイコンとリンク-->
            <%= link_to chats_path, method: :get, class: 'nav-link text-warning active' do %>
              <i class="fa-solid fa-comment-dots"></i>Chat
            <% end %>
            <!-- 通知のドロップダウンボタン -->
            <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="badge badge-danger"><%= Notification.notification_chat(current_user).count %></span>
            </button>
            <!-- 通知内容 ドロップダウンメニュー -->
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <% if Notification.notification_chat(current_user).any? %>
                <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                <% Notification.notification_chat(current_user).limit(5).order(created_at: :desc).each do |notification| %>
                  <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                <% end %>
              <% else %>
                <span class="dropdown-item disabled">未読の通知はありません</span>
              <% end %>
            </div>
          </li>
          <li>
            <%= link_to trips_path, method: :GET, class: 'nav-link text-warning active' do %>
            <i class="fa-solid fa-newspaper"></i><span>投稿一覧</span>
            <% end %>
          </li>
          <li>
            <%= link_to new_trip_path, method: :GET, class: 'nav-link text-warning active', data: {"turbolinks" => false} do %>
            <i class="fa-solid fa-signs-post"></i><span>新規投稿</span>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn nav-log-out', data: { confirm: "本当にログアウトしますか？" } do %>
            <i class="fa-solid fa-person-walking-arrow-right"></i><span>ログアウト</span>
            <% end %>
          </li>
        <% else %>
          <!--ユーザーサインアウト状態のヘッダー-->
          <li>
            <%= link_to new_user_registration_path, class: 'header-link nav-link', data: {"turbolinks" => false} do %>
            <i class="fa-solid fa-right-to-bracket"></i> 新規会員登録
          <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: 'header-link nav-link' do %>
            <i class="fa-regular fa-address-card"></i> ログイン
          <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<!--スクロールしたらヘッダーを透過するJavascript-->
<script>
  $(document).ready(function() {
    $(window).scroll(function() {
      if ($(this).scrollTop() > 0) {
        $('header').css('opacity', 0.9);
      } else {
        $('header').css('opacity', 1);
      }
    });
  });
</script>

app/views/layouts/_search_form.html.erb
<!--検索フォームの追加-->
<% if user_signed_in? %>
  <div class="search-form" %>
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([[t('search.options.user'), 'User'], [t('search.options.trip'), 'Trip']]) %>
      <%= f.submit "検索", class: "btn-sm btn-primary" %>
    <% end %>
  </div>
<% elsif admin_signed_in? %>
  <div class="search-form" %>
    <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([[t('search.options.user'), 'User'], [t('search.options.trip'), 'Trip']]) %>
      <%= f.submit "検索", class: "btn-sm btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_user_location_change.html.erb
<% if request.path == my_page_users_path %>
  <th class="pl-4">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      <i class="fa-solid fa-globe "></i>地域変更
    </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title fs-5" id="exampleModalLabel">住んでいる国・地域の変更</h3>
            <button type="button" data-dismiss="modal" aria-label="Close"><i class="fa-regular fa-circle-xmark" style="font-size:1.7rem"></i></button>
          </div>
          <%= form_with(model: user, local: true, multipart: true) do |f| %>
            <div class="modal-body">
              <!--Country 選択-->
              <div class="field my-3">
                <% already_registered_country = @user.country_id %>
                <%= f.label :住んでいる国 %><span class="mx-2 text-light p-1" style="background-color: #FF6600; font-size:0.8rem;"><%= "必須" %></span><br />
                <%= f.collection_select :country_id, Country.all, :id, :name, { include_blank: true }, { id: 'country_select' } %>
              </div>
              <!--Region 選択-->
              <div class="field mb-3">
                <%= f.label :住んでいる地域 %><span class="ml-2 text-light p-1" style="background-color: #FF6600; font-size:0.8rem;"><%= "必須" %></span><br />
                <%= f.select :region_id, [], { include_blank: true }, { id: 'region_select' } %>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
             <%= f.submit "変更する", class: 'btn btn-info' %>
            </div>
           <% end %>
        </div>
      </div>
    </div>
  </th>
<% end %>


<!--JSの記述 国を選択したら、関連した地域が出てくる-->
<script>
  document.addEventListener("turbolinks:load", function() {
  const countrySelect = document.getElementById('country_select');
  const regionSelect = document.getElementById('region_select');

  countrySelect.addEventListener('change', function() {
    const countryId = countrySelect.value;

    if (countryId) {
      fetch(`/countries/${countryId}/regions`)
        .then(response => response.json())
        .then(data => {
          regionSelect.innerHTML = ''; // 既存の選択肢をクリア

          data.forEach(region => {
            const option = document.createElement('option');
            option.value = region.id;
            option.text = region.name;
            regionSelect.appendChild(option);
          });
        });
    } else {
      regionSelect.innerHTML = ''; // 国が選択されていない場合、地域もクリア
    }
  });
  });
</script>

app/views/layouts/_user_show.html.erb
<!--以下がユーザー情報に関するコード-->
<div class="row d-flex justify-content-center mb-4 responsive-margin">
  <!--1. プロフィール写真表示-->
  <div class="col-lg-4 col-md-12 col-sm-12 justify-content-center text-center shadow border p-3" style="border-radius: 20px;">
   <h5 class="mb-3 border-bottom">プロフィール写真</h5>
   <%= image_tag user.get_profile_image, size: '150x150', class: 'rounded-circle' %>
  </div>
  <!--2. ユーザー基本情報表示-->
  <div class="col-lg-7 offset-lg-1 col-md-12 col-sm-12 shadow border p-3" style="border-radius: 20px;">
    <h5 class="mb-3 border-bottom text-center">基本情報</h5>
    <table>
      <tr>
        <th class="pr-3 pb-2">名前</th>
        <th class="pl-3 pb-2"><%= user.family_name %>  <%= user.first_name %></th>
      </tr>
      <tr>
        <th class="pr-3 pb-2">出身国</th>
        <th class="pl-3 pb-2"><%= user.nationality_country.name %></th>
      </tr>
      <tr>
        <th class="pr-3 pb-2">年齢</th>
        <th class="pl-3 pb-2"><%= user.age %></th>
      </tr>
      <tr>
        <th class="pr-3 pb-2">住んでいる地域</th>
        <th class="pl-3 pb-2">
          <% if user_signed_in? %>
            <%= link_to region_map_path(user.region_id), data: {"turbolinks" => false} do %>
            <i class="fa-solid fa-location-dot"></i>
            <%= user.country.name %>・<%= user.region.name %>
            <% end %><br/>
            <span class="d-none d-lg-inline-block" style="font-size: 0.9rem;">(地名をクリックすると、地図で場所の確認ができます)</span>
          <% else %>
            <%= user.country.name %>・<%= user.region.name %>
          <% end %>
        </th>
        <!--住んでいる地域を変更するボタンと編集Modalは部分テンプレート-->
        <%= render 'layouts/user_location_change', user: user %>
      </tr>
    </table>
  </div>
</div>

<div class="row d-flex justify-content-center rounded mb-4 responsive-margin">
  <!--3. ユーザー登録言語の情報を表示-->
  <div class="col-lg-4 col-md-12 col-sm-12 shadow border p-3" style="border-radius: 20px;">
    <h5 class="mb-3 border-bottom text-center">母国語と学習中の言語</h5>
    <table>
      <tr>
        <th class="pr-3 pb-2 py-2 border-bottom">母国語</th>
        <td class="pl-3 pb-2 py-2 border-bottom"><%= image_tag user.mother_language.flag, size: '40x40', class: 'rounded border mr-2' %><%= user.mother_language.name %></td>
      </tr>
      <tr>
        <th class="pr-3 pb-2 py-3">学習中の言語</th>
        <td class="pl-3 pb-2 py-3"><%= image_tag user.practice_language.flag, size: '40x40', class: 'rounded border mr-2' %><%= user.practice_language.name %></td>
      </tr>
    </table>
  </div>
  <div class="responsive-margin col-lg-7 offset-lg-1 col-md-12 col-sm-12 shadow border p-3" style="border-radius: 20px;">
    <!--4. 自己紹介 話したい話題を表示-->
    <div class="my-3">
      <h5 class="mb-3 border-bottom text-center">自己紹介・話したい話題</h5>
      <div class="my-2"><strong>自己紹介文</strong></div>
      <div class="border rounded p-2"><%= user.introduction %></div>
    </div>
    <div>
      <div class="my-2"><strong>話したい話題</strong></div>
      <div class="border rounded p-2"><%= user.topic %></div>
    </div>
  </div>
</div>

<div class="row d-flex justify-content-center mb-4 responsive-margin">
  <!--5. ユーザー写真(最大6枚は部分テンプレート-->
  <%= render 'layouts/user_slideshow', user: user %>

  <!--6. ユーザーが投稿した写真を最新4件表示する-->
  <div class="col-lg-7 offset-lg-1 col-md-12 col-sm-12 flex-wrap shadow border p-3" style="border-radius: 20px; background-color:#FFFFEE;">
    <h5 class="mb-3 border-bottom text-center">投稿した写真</h5>
      <div>
        <div class="text-center">
          <% if trips.empty? %>
            投稿画像がありません
          <% end %>
        </div>
        <% trips.first(4).each do |trip| %>
          <%= image_tag trip.get_trip_image, size: '100x90', class: 'mr-4 my-3' %>
        <% end %>
        <% if trips.empty? %>
          <% else %>
          <% if user_signed_in? %>
            <%= link_to "もっと見る", post_index_user_path(user), method: :GET, class: 'nav-link text-warning mr-5 text-right' %>
          <% elsif admin_signed_in? %>
            <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/_user_slideshow.html.erb
<!--5. ユーザー写真を表示する-->
<div class="col-lg-4 col-md-12 col-sm-12 flex-wrap shadow border p-3" style="border-radius: 20px; background-color:#EEFFFF;">
  <h5 class="mb-3 border-bottom d-flex justify-content-between align-items-center"><span class="mx-auto">ユーザー写真</span> <!-- 中央に配置 -->
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#slideModal">
      拡大
    </button>
  </h5>

  <!-- Modal -->
  <div class="modal fade" id="slideModal" tabindex="-1" aria-labelledby="slideModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="slideModalLabel">ユーザー写真</h1>
          <button type="button" data-dismiss="modal" aria-label="Close"><i class="fa-regular fa-circle-xmark" style="font-size:1.7rem"></i></button>
        </div>
        <div class="modal-body">
          <!--7. ユーザー写真のスライドショー-->
          <!--スライドショー(carousel)でサブ写真を表示する each_with_indexで取り出したデータそれぞれに0から番号を割り振る-->
          <!--carouselでは最初の画像にactiveクラスを与えないといけない-->
            <!--方法1 取り出した値にindex番号をつける 最初=0番のものはactiveクラスのdivになる！-->
          <p><span class="border-bottom">ユーザー写真スライドショー</span></p>
          <div class="d-flex mb-5">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="width:500px">
              <div class="carousel-inner">
                 <% user.sub_images.each_with_index do |sub_image, index| %>
                  <% if index == 0 %>
                    <div class="carousel-item active">
                      <%= image_tag sub_image, class: "d-block w-100", height: 300 %>
                    </div>
                  <% else %>
                    <div class="carousel-item">
                      <%= image_tag sub_image, class: "d-block w-100", height: 300 %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <%= link_to "#carouselExampleControls", role: "button", data: {slide: "prev"}, class: "carousel-control-prev" do %>
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            <% end %>
            <%= link_to "#carouselExampleControls", role: "button", data: {slide: "next"}, class: "carousel-control-next" do %>
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            <% end %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

   <% user.sub_images.each do |sub_image| %>
    <button type="button" class="user_slideshow-button" data-toggle="modal" data-target="#slideModal"><%= image_tag sub_image, size: '90x90', class: 'rounded mr-3 mb-3' %></button>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocalFriends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--Fontawesomeの読み込み-->
    <script src="https://kit.fontawesome.com/da08226a47.js" crossorigin="anonymous"></script>
    <!--chart.jsのCDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <main class="main-content d-flex justify-content-center flex-column">
      <%= yield %>
      <!-- Topへ戻るボタン -->
      <span style="position:fixed; bottom:30px; right:30px;">
        <%= link_to "#", id: "scroll-top" do %>
         <%= image_tag 'top_back2.png', size: '40x40' %>
        <% end %>
      </span>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>


    <!--jquery.jpostal.jsを使うためにCDNをで読み込む-->
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
</html>